use_frameworks!

platform :ios,’8.0’
abstract_target '' do


pod 'SDWebImage', '~> 4.0.0'
pod 'Masonry', '~>1.0.2'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'BlocksKit'
pod 'MJExtension', '~> 3.0.13'
pod 'Reachability', '~> 3.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'FLEX', :configurations => ['Debug']
pod 'Toast', '~> 4.0.0'
pod 'JPush'

target 'RNAndiOSCallEachOther'

end
